"""api key table

Revision ID: 7991169a5f38
Revises: 0f92ab804543
Create Date: 2025-11-27 17:26:15.077037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7991169a5f38'
down_revision: Union[str, Sequence[str], None] = '0f92ab804543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikey',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('secret_digest', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apikey_prefix'), 'apikey', ['prefix'], unique=False)
    op.alter_column('category', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('category', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('tag', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('tag', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('testimonial', sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('testimonial', sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('testimonial', sa.Column('youtube_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('testimonial', sa.Column('image_url', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('testimonial', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('testimonial', sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('testimonial', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.alter_column('testimonial', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('testimonial', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('testimonial', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('testimonial', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('testimonial_author_id_fkey'), 'testimonial', type_='foreignkey')
    op.drop_constraint(op.f('testimonial_category_id_fkey'), 'testimonial', type_='foreignkey')
    op.create_foreign_key(None, 'testimonial', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'testimonial', 'category', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('testimonial', 'media_type')
    op.drop_column('testimonial', 'views_count')
    op.drop_column('testimonial', 'author_id')
    op.drop_column('testimonial', 'media_url')
    op.add_column('user', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('role', sa.Enum('ADMIN', 'MODERATOR', 'USER', name='roles'), nullable=False))
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_column('user', 'password')
    op.drop_column('user', 'roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('roles', postgresql.ENUM('ADMIN', 'MODERATOR', 'USER', name='roles'), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('user', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('user', 'role')
    op.drop_column('user', 'hashed_password')
    op.add_column('testimonial', sa.Column('media_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('testimonial', sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('testimonial', sa.Column('views_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('testimonial', sa.Column('media_type', postgresql.ENUM('IMAGE', 'VIDEO', 'TEXT', name='mediatype'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'testimonial', type_='foreignkey')
    op.drop_constraint(None, 'testimonial', type_='foreignkey')
    op.create_foreign_key(op.f('testimonial_category_id_fkey'), 'testimonial', 'category', ['category_id'], ['id'])
    op.create_foreign_key(op.f('testimonial_author_id_fkey'), 'testimonial', 'user', ['author_id'], ['id'])
    op.alter_column('testimonial', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('testimonial', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('testimonial', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('testimonial', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('testimonial', 'user_id')
    op.drop_column('testimonial', 'author_name')
    op.drop_column('testimonial', 'rating')
    op.drop_column('testimonial', 'image_url')
    op.drop_column('testimonial', 'youtube_url')
    op.drop_column('testimonial', 'product_name')
    op.drop_column('testimonial', 'product_id')
    op.alter_column('tag', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('tag', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('category', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('category', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_apikey_prefix'), table_name='apikey')
    op.drop_table('apikey')
    # ### end Alembic commands ###
