"""update user for multy tenancy

Revision ID: c36d11daa061
Revises: 7991169a5f38
Create Date: 2025-12-06 22:10:46.573588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c36d11daa061'
down_revision: Union[str, Sequence[str], None] = '7991169a5f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('user')]

    # Update enum type from uppercase to lowercase
    op.execute("ALTER TYPE roles RENAME TO roles_old")
    op.execute("CREATE TYPE roles AS ENUM ('owner', 'admin', 'moderator')")
    op.execute("""
        ALTER TABLE "user" ALTER COLUMN role TYPE roles
        USING CASE
            WHEN role::text = 'ADMIN' THEN 'admin'::roles
            WHEN role::text = 'MODERATOR' THEN 'moderator'::roles
            WHEN role::text = 'USER' THEN 'owner'::roles
            ELSE role::text::roles
        END
    """)
    op.execute("DROP TYPE roles_old")

    # Add multitenancy column (only if it doesn't exist)
    if 'owner_id' not in columns:
        op.add_column('user', sa.Column('owner_id', sa.Uuid(), nullable=True))
        op.create_foreign_key('fk_user_owner_id', 'user', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('user')]

    # Drop multitenancy column (only if it exists)
    if 'owner_id' in columns:
        op.drop_constraint('fk_user_owner_id', 'user', type_='foreignkey')
        op.drop_column('user', 'owner_id')

    # Revert enum type changes (mapping new to old values)
    op.execute("ALTER TYPE roles RENAME TO roles_new")
    op.execute("CREATE TYPE roles AS ENUM ('ADMIN', 'MODERATOR', 'USER')")
    op.execute("""
        ALTER TABLE "user" ALTER COLUMN role TYPE roles
        USING CASE
            WHEN role::text = 'admin' THEN 'ADMIN'::roles
            WHEN role::text = 'moderator' THEN 'MODERATOR'::roles
            WHEN role::text = 'owner' THEN 'USER'::roles
            ELSE role::text::roles
        END
    """)
    op.execute("DROP TYPE roles_new")
    # ### end Alembic commands ###
